version: "3"
services:
  web:
    image: weather-app-server
    container_name: weather-app-server
    ports:
        - "3000:3000"
    links:
      - mongo
      - redis
    environment:
      - DEBUG=1
      - PORT=3000
      - REDIS_PORT=6379
      - REDIS_CONTAINER=redis
      - MONGODB_PORT=27017
      - MONGODB_CONTAINER=mongo
      - JWT_KEY=djghhhhuuwiwuewieuwieuriwu
      - CWB_KEY=CWB-CC1F57A7-A9CA-46BC-9B8F-381DF1D13D5A
  mongo:
     image: mongo
     container_name: mongo
     ports:
        - "27017:27017"
  redis:
    image: redis
    container_name: redis
    ports:
        - "6379:6379"